version: "3.9"
services:
  greenplum:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DBNAME=$POSTGRES_DBNAME
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER" ]
      interval: 5s
      timeout: 10s
      retries: 5
  fashion-mnist-classifier:
    build: .
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DBNAME=$POSTGRES_DBNAME
      - POSTGRES_DBHOST=greenplum
      - POSTGRES_DBPORT=5432
    command: >
      bash -c "
        coverage run src/unit_tests/test_datasets.py &&
        coverage run src/unit_tests/test_training_results.py &&
        coverage report -m
        "
    image: ${DOCKER_IMAGE_TAG_NAME}
    links:
      - "greenplum:database"
    depends_on:
      greenplum:
        condition: service_healthy