version: "3.9"
services:
  fashion-mnist-classifier:
    build: .
    command: >
      sh -c "
        coverage run src/unit_tests/test_datasets.py &&
        coverage run src/unit_tests/test_training_results.py \
          --db-user=${POSTGRES_USER} \
          --db-password=${POSTGRES_PASSWORD} \
          --db-name=${POSTGRES_DBNAME} &&
          --db-host=greenplum &&
          --db-port=5432 &&
        coverage report -m
        "
    image: ${DOCKER_IMAGE_TAG_NAME}
    links:
      - "greenplum:database"
    depends_on:
      greenplum:
        condition: service_healthy
  greenplum:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DBNAME}" ]
      timeout: 20s
      retries: 5