version: "3.9"
services:
  fashion-mnist-classifier:
    build: .
    command: >
      sh -c "
        coverage run src/unit_tests/test_datasets.py &&
        coverage run src/unit_tests/test_training_results.py &&
        coverage report -m
        "
    image: izhanvarsky/bigdata-hw1-fashion-mnist-classifier:latest