name: CI - Build and push docker image to dockerhub

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set image and tag names in env
        env:
          IMAGE_NAME: bigdata-hw1-fashion-mnist-classifier
        run: |
          echo "DOCKER_LATEST_TAG_NAME=izhanvarsky/$IMAGE_NAME:latest" >> "$GITHUB_ENV"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: izhanvarsky
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data from DVC
        run: |
          dvc pull
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_LATEST_TAG_NAME }}
