name: CD - run tests in docker container

on:
  workflow_run:
    workflows:
      - CI - Build and push docker image to dockerhub
    types:
      - completed

jobs:
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: izhanvarsky
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull with compose
        run: docker-compose pull
      - name: Create .env file
        run: |
          touch .env
          echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" >> .env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo POSTGRES_DBNAME="${{ secrets.POSTGRES_DBNAME }}" >> .env
      - name: Run tests
        run: docker-compose up --abort-on-container-exit